name: Update README with stars
on: push

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 387273
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2025
      - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
        with:
          commit_message: Update README stars